- pnpm-lock.yaml
- src/api/check.ts
- src/cli.ts
- src/commands/check.ts
- src/types.ts
when run taze in Monorepo, maybe some packages is up to date, but still shown out.
I add a feature, it will auto hide the package that is up to date and show a log like below pic.
> feat(show): hide update packages

- src/commands/check.ts
It is common that, in full-stack projects, a `package.json` has no `name` property because it is not relevant. In those case, `taze` displays `undefined` in place of the package name.
This PR proposes to replace `undefined` with the `›` symbol, or any other arrow. It could also be something like "unnamed project" or something else along those lines, but I wasn't sure about that and felt like a simple symbol was the best replacement.
**Note**: I didn't test this change, I PR'd via the GitHub interface, and [I couldn't just `npx` my branch](https://i.imgur.com/KmoePuZ.png). Given the simplicity of the PR it shouldn't matter, but I suggest you check it locally before merging if you decide to do so.
> fix: replace `undefined` with `›`

- src/cli.ts
- src/commands/check.ts
- src/types.ts
This PR implements a `loglevel` option to suppress warnings by default.
Closes #6.
> feat: implement loglevel option

- src/utils/versions.ts
- test/resolves.test.ts
- test/versions.test.ts
#11 
try to fix these problems below
1. abend in default mode (situation of Issues 11)
2. current version has the same error in newest mode (whatever the package version is)
3. package version can be blank (same meaning of *)
Now the behavior is
if the package version is (* or blank) and in mode (default or newest), will not be updated
Hope I am right :)
> fix: improve version handling

- README.md
When working in #29 I see the repo has a `.tazerc.json` file, a feature I want but didn't know it's exists!
So I added a small section in the readme, you can freely improve, it's a bit rough.
> docs: add config file section

- src/commands/check/index.ts
This PR which fixes #38  is to improve the write tip for `major` mode. Right now when you run `taze major` the tip prints out:
```
Run taze -w to write package.json
```
Which is misleading since the `taze -w` will run the default mode. To fix this, we change it to:
```
Add -w to write package.json
```
Which will cover all modes ✅
> refactor: improve write tip for major mode

- src/cli.ts
- src/commands/check/index.ts
- src/types.ts
This PR adds the `--fail-on-outdated` option (usable both from cli and config file) that makes taze exit with code 1 when outdated dependencies are found (useful for CI use).
fixed #56
> feat: added --fail-on-outdated option #56

- src/index.ts
replacing `CommonOptions` with `CheckOptions`
#60
> As it says in readme, all options command supported are also supported by defineConfig function.
> However the generic type of defineConfig is CommonOptions which doesn't cover all command options.
When receiving fields such as write or install, defineConfig indeed encounters type errors. I fixed this issue in this PR.
https://github.com/antfu/taze/issues/60
> fix: defineConfig type error (#60)

- src/commands/check/index.ts
- src/commands/check/render.ts
No error message was printed when the request went wrong（For example, my npm CA setting is wrong）
After this PR fix, the error can be printed
> fix: no output error when network error

- src/commands/check/interactive.ts
Some users are accustomed to using vi-style `hjkl` movements in various CLI tools, including `npm-check` and `prompts`.
This change adds `hjkl` vi-style bindings to the interactive mode.
The PR also changes the syntax construct for bindings from `if/else if` to switch. The reason for preferring switch here is to avoid long lines and mental parsing. In all cases but one, each case ended either with a `return` statement or `process.exit()`. In the single exceptional case, a `break` statement was added. If this change is accepted, it will be easier to visually grep for keybindings or to add or update keycodes (one line per binding, for easier git diffs)
Note also that this PR does not change the help text, as `hjkl` use is an 'advanced' feature
> feat: vim-style bindings for interactive mode

- src/commands/check/checkGlobal.ts
Filter `pnpmOuts`
An error occurred while running `taze -g` with the following error message.
```
TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at file:///D:/scoop/persist/nvm/nodejs/v16.20.1/node_modules/taze/dist/cli.mjs:819:25
at Array.map (<anonymous>)
at loadGlobalPnpmPackage (file:///D:/scoop/persist/nvm/nodejs/v16.20.1/node_modules/taze/dist/cli.mjs:818:29)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 1)
at async checkGlobal (file:///D:/scoop/persist/nvm/nodejs/v16.20.1/node_modules/taze/dist/cli.mjs:749:22)
at async Object.handler (file:///D:/scoop/persist/nvm/nodejs/v16.20.1/node_modules/taze/dist/cli.mjs:978:18)
```
The error occurs because the dependencies field is missing, because …
> fix: loadGlobalPnpmPackage throws TypeError

- src/utils/npm.ts
`@npmcli/config` added on #51, and `npmcliConfig.load()` would set some env variables, and this behavior cannot be turned off with configuration. It will fail when installing global modules for nodejs installed with homebrew on macOS. 
And I didn't find that useful of those env, so set it back to the original env after `load()` to avoid this problem.
#51
> fix: global package install on macOS with Homebrew nodejs

- src/commands/check/render.ts
- src/io/resolves.ts
- src/render.ts
- src/types.ts
- src/utils/diff.ts
- test/resolves.test.ts
It's important to determine what `major`,`minor`,`patch` mean.
<table>
<tr>
<td>
<td>change type
<tr>
<td>0.3.4 -> 0.3.7
<td>patch
<tr>
<td>0.3.4 -> 0.4.6
<td>minor
<tr>
<td>0.0.3 -> 0.0.4
<td>patch
</table>
Note: `semver.diff` has other types: `premajor, preminor, prepatch, prerelease`, e.g.:  
<table>
<tr>
<td>
<td>change type
<tr>
<td>0.3.4 -> 0.3.7
<td>patch
<tr>
<td>0.3.4 -> 0.4.6
<td>major
<tr>
<td>0.0.3 -> 0.0.4
<td>major
</table>
Note: `^` simply means allowing changes that do not modify the left-most non-zero version number.
<table>
<tr>
<td>
<td>change type
<tr>
<td>0.3.4 -> 0.3.7
<td>major
<tr>
<td>0.3.4 -> 0.4.6
<td>major
<tr>
<td>0.0.3 -> 0.0.4
<td>major
</table>
`colorizeVersionDiff`:
```ts
export function colorizeVersionDiff(from: string, to: string, hightlightRange = true) …
```
> feat: more sensible counter and version color

- src/commands/check/interactive.ts
- src/commands/check/render.ts
- src/render.ts
In interactive mode, if our terminal is too short or our deps are too many, we cannot see all deps.
When we use arrow keys to move the selection, the user experience is not good. Especially, when the selection is in the start part, everytime I move the selection, the terminal just scroll back to the bottom, and I can't see the selection anymore. So I have to drag to enlarge the terminal area. But what if our deps are so many that whole screen cannot embrace them or we just don't want to do the drag.
So I made the pr. The method I use is: only render a part of output lines if there is no enough space.
There is no issue about this now. Feel free to reject this if you consider it not appropriate.
> feat: make long list scrollable for interactive mode

- src/cli.ts
- src/config.ts
- src/constants.ts
- src/io/packages.ts
- src/log.ts
- src/types.ts
- src/utils/sort.ts
- test/packageConfig.test.ts
Also fixes some configuration types.
If I got something wrong, please let me know, I will fix it ASAP.
closes #87
> fix: respect config file when no explicit cli flags

- src/commands/check/index.ts
Placeholder `{name}` shouldn't be visible.
> chore: fix flicker placeholder for dep bar

- package.json
- tsconfig.json
This pull request includes updates to the tsconfig.json file, aligning it with modern development practices. The changes introduced are as follows:
- `"moduleResolution": "Bundler"`: Since TypeScript 5.0, the "moduleResolution" configuration now deprecates the Node.js resolution modes ("Node" and "Node10") in favor of "Bundler". This setting is designed for compatibility with bundlers. In contrast to the Node.js resolution modes, the "Bundler" mode allows seamless usage of "imports" and "exports" without the need for file extensions on relative paths in imports.
- `"moduleDetection": "force"`: Enabling this option ensures that every non-declaration file is treated as a module, providing a more consistent and predictable module handling approach.
- `"isolatedModules": true`: TypeScript …
> chore: improve tsconfig

- src/cli.ts
- src/constants.ts
- src/io/dependencies.ts
- src/io/packages.ts
- src/types.ts
- test/dumpDependencies.test.ts
- test/parseDependencies.test.ts
Edit by @antfu:
Breaking change:
This PR removes the `--prod` and `--dev` cli arguments along with their config entry. As a replacement, a `depFields` option field is introduced in `taze.config.ts` with more granular control of each field to bump. 
----
closes: #70 
Great project here! I use it for dependency updates in every project. I feel the need to automatically update `pnpm.overrides` with other dependencies. There already was an issue open for that, so I just implemented it.
What's changed:
- accessing package keys is now available for deep keys like `pnpm.overrides`
- keys `pnpm.overrides` and `resolutions` are added
- added a few tests to make sure that touched areas are not broken
I also tested a locally built package on monorepo, all worked well with the addition for overrides:
> feat!: support `pnpm.overrides` and `resolutions`, remove `--dev` and `--prod` cli option

- src/render.ts
When the version in package.json is incomplete, such as ^18 or ^18.2, SemVer will throw an exception.
> fix: invalid version

- src/render.ts
Sorry to make a mistake, I forget to check both ◉ and ◌ when counting deps.
This causes scroll of interactive mode to work abnormally when there are deps unchecked.
> fix: interactive scroll

- README.md
- src/io/dependencies.ts
- src/io/resolves.ts
- src/types.ts
- src/utils/package.ts
- test/dumpDependencies.test.ts
- test/parseDependencies.test.ts
- test/resolves.test.ts
Fix support for `overrides`, `pnpm.overrides` and `resolutions` by handling properly nested dependencies and package managers custom syntaxes.
[NPM allows you to specify a full object for **overrides** field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides). 
Fix the `"TypeError: currentVersion.startsWith is not a function"` error.
Output with the latest version:
Output now:
Fix support for [custom ">" dependency selector](https://pnpm.io/pt/next/package_json#pnpmoverrides) used to target nested dependencies.
Fix the `Invalid package name` error.
Output with the latest version:
Output now:
Fix support for [nested resolutions custom syntax](https://classic.yarnpkg.com/en/docs/package-json#toc-resolutions) for Yarn.
Fix the `ENOENT: no such file or directory` error. …
> fix: support nested `resolutions` and `overrides`

- src/commands/check/interactive.ts
In interactive mode, allows users to press `a` to select/deselect all dependencies. If all dependencies are selected `a` will deselect all, otherwise it will select all.
- https://github.com/antfu/taze/issues/85
> feat: `a` to select all packages in interactive mode

- .github/workflows/ci.yml
The CI of #109 failed due to the outdated version of Node.js used to run the lint workflow. The PR updates the GitHub Action to fix that.
#109
N/A
> ci(lint): use node `lts/*`

- build.config.ts
- package.json
- pnpm-lock.yaml
- src/cli.ts
- test/cli.test.ts
#111 is caused by the Rollup (`unbuild` uses Rollup under the hood) incorrectly bundling `@npmcli/config` (and its transitive dependency `cacache`, which requires its own `package.json`).
The PR provides a workaround by changing how dists are bundled. A test case has also been added to ensure the CLI itself should never crash.
#111
This is a workaround that works for now. I am still investigating a better solution that solves the issue once and for all.
Here are the backgrounds behind #111 and this PR:
- `@npmcli/config` requires `cacache`, and `cacache` requires its own `package.json`. This causes `@rollup/plugin-commonjs` to panic. Instead of using the correct named exports generated from `@rollup/plugin-json`, `@rollup/plugin-commonjs` try to wrap the exports with its interop code, …
> fix: change the build config to bundle deps correctly, fix #111

- package.json
- pnpm-lock.yaml
- src/commands/check/checkGlobal.ts
- test/cli.test.ts
I first encountered the package `@jsdevtools/ez-spawn` through [`bumpp`](https://github.com/antfu-collective/bumpp/blob/3e90d138c6e2fb7e7e1e5344fd359543567bd658/package.json#L62), which uses `exspawn` under the hood.
Though no longer being actively maintained, `ezspawn` already fulfills almost every use case and doesn't suffer from breaking bugs.
`@jsdevtools/ez-spawn` has fewer dependencies than `execa` and takes up only 47% of the disk space (the installation size of `@jsdevtools/ez-spawn` is [142 KiB](https://pkg-size.dev/@jsdevtools%2Fez-spawn) compared to `execa` at [301 KiB](https://pkg-size.dev/execa)). Moreover, its usage is extremely straightforward. Unlike `execa`, which has separated `execa` and `execCommand`, `ezspawn`'s single method can perform both functions.
> refactor: replace `execa` w/ `ezspawn`

- src/constants.ts
- src/types.ts
- src/utils/versions.ts
- test/versions.test.ts
Prior to #37, `taze newest` would specifically target the `next` tag of a package. #37 altered this to target the most recently published version of the package.
I appreciate the modification introduced by #37 (it does make sense), but occasionally, I need to bump the `next` tag of a package rather than the most recently published version. `eslint-plugin-react-hooks` would be an example of the case:
So I introduce a new mode `next` that brings the old behavior back.
> feat: new mode `next`

- src/commands/check/interactive.ts
- src/commands/check/render.ts
- src/types.ts
This PR fixes the issue when navigation in the list of dependencies in the interactive mode is not synced with actual rendered list on the screen when navigating.
Changes:
- Resolved packages dependencies are sorted each time version is changed by renderer created with `createVersionSelectRender`.
- `interactiveChecked` property removed from `ResolvedDepChange`, because related functionality was refactored to use `Set` instead, which makes code more readable and isolates the interactivity-related functionality.
- `interactiveChecked` property removed from `PackageMeta` since it's not used anywhere.
Fixes #132.
The issue fixed in this PR may still arise later, because rendered dependencies are implicitly kept in sync with actual rendering in `renderChanges` function. For now I didn't come …
> fix: sync navigation with rendering in interactive mode

- src/addons/vscode.ts
> fix(vscode): with lock version

- package.json
- pnpm-lock.yaml
- src/commands/check/checkGlobal.ts
- test/cli.test.ts
Replacing `ezspawn` with a even lighter library, see also https://github.com/antfu/install-pkg/pull/14
N/A
https://github.com/antfu/install-pkg/pull/14
> refactor: replace `ezsapawn` w/ `tinyexec`

- package.json
- pnpm-lock.yaml
Re-land #109 for #138.
`npm-registry-fetch` was replaced by `ofetch` and was then brought back (https://github.com/antfu-collective/taze/commit/4a62457fd2680eed4784a28a79015e20b739fed2) to fix #122. But in the process `npm-registry-fetch` is no longer bundled.
#138
N/A
> chore: bundle `npm-registry-fetch`

- package.json
- pnpm-lock.yaml
- src/cli.ts
Just like the title, when you press `ctrl+c` to exit when installing, cursor in terminal will hide.
> fix: cursor loss when exiting during installation

- src/addons/vscode.ts
This PR adds versions check for addon vscode.
Only sync when `engins.vscode`'s version is smaller than `@types/vscode`'s.
Fix https://github.com/antfu-collective/taze/issues/144
None.
> fix(vscode): check versions before sync

- src/addons/vscode.ts
I encountered this error when updating
```
TypeError: Invalid Version: ^1.92.0
at new SemVer (file:///Users/hyoban/.npm/_npx/16d8e2cf83f8302f/node_modules/taze/dist/shared/taze.GGCFjr0T.mjs:7954:14)
at compare (file:///Users/hyoban/.npm/_npx/16d8e2cf83f8302f/node_modules/taze/dist/shared/taze.GGCFjr0T.mjs:8438:33)
at Object.gt (file:///Users/hyoban/.npm/_npx/16d8e2cf83f8302f/node_modules/taze/dist/shared/taze.GGCFjr0T.mjs:8515:30)
at Object.beforeWrite (file:///Users/hyoban/.npm/_npx/16d8e2cf83f8302f/node_modules/taze/dist/shared/taze.GGCFjr0T.mjs:10218:27)
at writePackageJSON (file:///Users/hyoban/.npm/_npx/16d8e2cf83f8302f/node_modules/taze/dist/shared/taze.GGCFjr0T.mjs:10340:32)
at writePackage (file:///Users/hyoban/.npm/_npx/16d8e2cf83f8302f/node_modules/taze/dist/shared/taze.GGCFjr0T. …
```
> fix: invalid version when checking vscode engine

- src/cli.ts
- src/commands/check/interactive.ts
- src/commands/check/render.ts
- src/types.ts
Adds the `-t` option to hide the `time diff` on the updating version screen. 
Fixes #148
Suggestions for better option name or different approach are welcomed
> feat: add `timediff` option

- src/commands/check/index.ts
The message after running `taze -w` (without autoinstall) was hardcoded to `run npm i to install updates.`
This PR uses `detect()` from `ni` to show the correct package manager.
> chore: detect package manager to show in message after writing

- src/commands/check/checkGlobal.ts
If you don't select `npm` global packages but choose other packages, the program will encounter an error due to command `npm i -g`.
```
❯ npm i -g
npm error code ENOENT
npm error syscall open
npm error path /Users/kevin/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/kevin/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /Users/kevin/.npm/_logs/2025-02-02T20_42_50_448Z-debug-0.log
```
> fix(global): handle select no global npm packages

- src/commands/check/index.ts
Add `--no-save` flag to prevent updating ranges in `package.json`
See https://pnpm.io/cli/update#--no-save
> fix: add `--no-save` for `pnpm upgrade`

- src/utils/npm.ts
- src/utils/npmcliConfig.d.ts
Hey folks, this fix adds a missing param to the construction of `Config` from `@npmcli/config`—see [here](https://github.com/npm/cli/blob/config-v10.3.1/workspaces/config/lib/index.js#L69) for the non-optional param in the source of the package.
This removes errors that can occur during `await npmcliConfig.load()` [here](https://github.com/antfu-collective/taze/blob/cc4df7780fa9bb8bce9c2beedb8300ae7f808246/src/utils/npm.ts#L36). The errors probably stop part of taze's dep crawl, but I didn't dive very deep after coming up with this fix.
```
TypeError: Cannot convert undefined or null to object
```
<details><summary>🖼️ Errors example</summary>
<p>
</p>
</details> 
fix #196
Prior to [this change](https://github.com/npm/cli/commit/593c84921b0df963cef2ca7b13e44acc20cbd558#diff-cde3afb35a673142 …
> fix: npm cli config load errors

- src/cli.ts
- src/commands/check/interactive.ts
- src/constants.ts
- src/io/resolves.ts
- src/types.ts
- src/utils/versions.ts
- test/versions.test.ts
This PR implements a maturity period option that allows users to wait for a period of time before upgrading to newly released package versions.
Filters out deprecated versions and prevents packages with deprecated current versions from being processed.
Filters out versions that are under a specified days of maturity dates from being processed.
Fixes #202
```console
taze
taze --maturity-period
taze --maturity-period 14
taze --maturity-period 1
taze --maturity-period 7 --mode minor --write
```
I'm not sure this is exactly what you want for this feature, from the description of issue.
- Is `--maturity-period` meaningful for this feature?
- Is the `7 days` appropriate default value?
And in several cases you've seen, please feel free to discuss with me.
If you have any suggestions or want me …
> feat: add maturity period option to filter newly released packages
